### ISSUE TITLE
Accessories not showing up in HomeKit.

### ISSUE THREAD

**Issue by sricks1** [nitaybz/homebridge-sensibo-ac#72]
I have installed the plugin and configured my device using both the key and user name and password.  I have tried them individually and together.  The log says it is up and running.  I set up my bridge in HomeKit, but no accessories show up.  I am trying to connect a SensiboAC.  Here is my log;  

fields=id,acState,measurements,remoteCapabilities,room,temperatureUnit,productModel,location,occupancy,smartMode,motionSensors,filtersCleaning,serial,pureBoostConfig,homekitSupported
10/5/2021, 9:57:18 PMSensibo Ac BridgeSensiboACSuccessful GET response:
10/5/2021, 9:57:18 PMSensibo Ac BridgeSensiboAC[]
10/5/2021, 9:58:48 PMSensibo Ac BridgeSensiboACCreating GET request to Sensibo API --->
10/5/2021, 9:58:48 PMSensibo Ac BridgeSensiboAChttps://home.sensibo.com/api/v2/users/me/pods?fields=id,acState,measurements,remoteCapabilities,room,temperatureUnit,productModel,location,occupancy,smartMode,motionSensors,filtersCleaning,serial,pureBoostConfig,homekitSupported
10/5/2021, 9:58:49 PMSensibo Ac BridgeSensiboACSuccessful GET response:
10/5/2021, 9:58:49 PMSensibo Ac BridgeSensiboAC[]
10/5/2021, 10:00:19 PMSensibo Ac BridgeSensiboACCreating GET request to Sensibo API --->
10/5/2021, 10:00:19 PMSensibo Ac BridgeSensiboAChttps://home.sensibo.com/api/v2/users/me/pods?fields=id,acState,measurements,remoteCapabilities,room,temperatureUnit,productModel,location,occupancy,smartMode,motionSensors,filtersCleaning,serial,pureBoostConfig,homekitSupported
10/5/2021, 10:00:20 PMSensibo Ac BridgeSensiboACSuccessful GET response:
10/5/2021, 10:00:20 PMSensibo Ac BridgeSensiboAC[]

**Comment by ndarmyserver** [comment]
I'm having a similar issue. The plugin is installed and configured, and I see a successful get request in the logs, but no Sensibo device shows up in my Home app. If I downgrade this plugin to 2.1.8, my device shows up in the Home app. It is only on the 2.2.0 version that it doesn't work correctly.

**Comment by dVIAN13** [comment]
I am having the same issue. older plugin version did not fix it.. I see in the logs that it creates the accessory, but never appears in HomeKit.

If I setup the Sensibo plugin to use it's own bridge, it works

**Comment by adavison007** [comment]
> I'm having a similar issue. The plugin is installed and configured, and I see a successful get request in the logs, but no Sensibo device shows up in my Home app. If I downgrade this plugin to 2.1.8, my device shows up in the Home app. It is only on the 2.2.0 version that it doesn't work correctly.

I have this same issue, 2.1.8 works with AirQ but not 2.2.0

**Comment by benwebbbenwebb** [comment]
For those looking for a fix, I have submitted a PR, #94, for this issue.

As a workaround (until it is merged) please see my alternate NPM package https://www.npmjs.com/package/@benwebbbenwebb/homebridge-sensibo-ac

**Comment by adavison007** [comment]
> For those looking for a fix, I have submitted a PR, #94, for this issue.
> 
> As a workaround (until it is merged) please see my alternate NPM package https://www.npmjs.com/package/@benwebbbenwebb/homebridge-sensibo-ac

Any idea of a rough timeline for the merge?

**Comment by benwebbbenwebb** [comment]
Please upgraded to v2.3.3 and let me know about any issues, that version should include Air and Air Plus devices

**Comment by adavison007** [comment]
Upgrade done, so far, so good, brilliant, many thanks, much appreciated.

**Comment by kapps7** [comment]
Hey guys. Similarly I have a Sky and logs confirm that 1 accessory is loaded but Homebridge doesn't show it in the accessories and ofcourse not into Homekit

**Comment by benwebbbenwebb** [comment]
Hi @kapps7 
Sounds similar to #97, would you be able to provide your Sensibo API response?

**Comment by benwebbbenwebb** [comment]
Closing this issue as I think it's now all resolved with the 2.3.4-release

**Comment by ndarmyserver** [comment]
@benwebbbenwebb sorry to bring up an old thread, but I'm still having issues with this, even on 2.3.4. I get a successful get response, but my device doesn't show up in the Home app. In the get response it shows "productModel":"inside" Let me know if you need any more information. I'm still able to downgrade to 2.1.8 the device shows up. Thanks

**Comment by benwebbbenwebb** [comment]
Hi @ndarmyserver 

Sure, I’ll take a look.

Thanks for providing the productModel, what does “inside” map to? Is it the Elements sensor? (E.g. #103)

If not, then I’ll need an example payload to understand what features, attributes and measurements it returns.

**Comment by ndarmyserver** [comment]
@benwebbbenwebb sorry again to bring up this old issues, but I'm still experiencing it on version 2.5.1. Below is a what I'm seeing in the homebridge console. It still works in 2.1.8. Let me know if you need anything else
`[10/29/2025, 12:56:34 PM] [SensiboAC] Refreshing state...`
`[10/29/2025, 12:56:34 PM] [SensiboAC] Creating GET request to Sensibo API ->`
`[10/29/2025, 12:56:34 PM] [SensiboAC] https://home.sensibo.com/api/v2/users/me/pods?fields=id,acState,measurements,location,occupancy,smartMode,motionSensors,filtersCleaning,serial,pureBoostConfig,homekitSupported,remoteCapabilities,room,temperatureUnit,productModel`
`[10/29/2025, 12:56:34 PM] [SensiboAC] Successful GET response:`
`[10/29/2025, 12:56:34 PM] [SensiboAC] [
    {
        "id": "**********",
        "temperatureUnit": "F",
        "room": {
            "uid": "**********",
            "name": "Garage",
            "icon": "Lounge",
            "pureBoostConfig": null
        },
        "acState": {
            "timestamp": {
                "time": "2025-10-29T17:56:34.880373Z",
                "secondsAgo": 0
            },
            "on": false,
            "mode": "cool",
            "targetTemperature": 67,
            "temperatureUnit": "F",
            "fanLevel": "medium",
            "swing": "rangeFull",
            "light": "on"
        },
        "location": {
            "occupancy": "n/a",
            "name": "**********",
            "id": "**********"
        },
        "productModel": "inside",
        "serial": "**********",
        "motionSensors": [],
        "filtersCleaning": {
            "acOnSecondsSinceLastFiltersClean": 34594,
            "filtersCleanSecondsThreshold": 1080000,
            "lastFiltersCleanTime": {
                "time": "2025-07-18T20:43:30Z",
                "secondsAgo": 8889184
            },
            "shouldCleanFilters": false
        },
        "pureBoostConfig": null,
        "homekitSupported": false,
        "remoteCapabilities": {
            "modes": {
                "cool": {
                    "temperatures": {
                        "F": {
                            "isNative": true,
                            "values": [
                                62,
                                63,
                                64,
                                65,
                                66,
                                67,
                                68,
                                69,
                                70,
                                71,
                                72,
                                73,
                                74,
                                75,
                                76,
                                77,
                                78,
                                79,
                                80,
                                81,
                                82,
                                83,
                                84,
                                85,
                                86
                            ]
                        },
                        "C": {
                            "isNative": false,
                            "values": [
                                17,
                                18,
                                19,
                                20,
                                21,
                                22,
                                23,
                                24,
                                25,
                                26,
                                27,
                                28,
                                29,
                                30
                            ]
                        }
                    },
                    "fanLevels": [
                        "quiet",
                        "low",
                        "medium",
                        "high",
                        "auto",
                        "strong"
                    ],
                    "swing": [
                        "stopped",
                        "rangeFull"
                    ],
                    "light": [
                        "on",
                        "off"
                    ]
                },
                "heat": {
                    "temperatures": {
                        "F": {
                            "isNative": true,
                            "values": [
                                46,
                                62,
                                63,
                                64,
                                65,
                                66,
                                67,
                                68,
                                69,
                                70,
                                71,
                                72,
                                73,
                                74,
                                75,
                                76,
                                77,
                                78,
                                79,
                                80,
                                81,
                                82,
                                83,
                                84,
                                85,
                                86
                            ]
                        },
                        "C": {
                            "isNative": false,
                            "values": [
                                8,
                                17,
                                18,
                                19,
                                20,
                                21,
                                22,
                                23,
                                24,
                                25,
                                26,
                                27,
                                28,
                                29,
                                30
                            ]
                        }
                    },
                    "fanLevels": [
                        "quiet",
                        "low",
                        "medium",
                        "high",
                        "auto",
                        "strong"
                    ],
                    "swing": [
                        "stopped",
                        "rangeFull"
                    ],
                    "light": [
                        "on",
                        "off"
                    ]
                },
                "fan": {
                    "temperatures": {},
                    "fanLevels": [
                        "quiet",
                        "low",
                        "medium",
                        "high",
                        "auto",
                        "strong"
                    ],
                    "swing": [
                        "stopped",
                        "rangeFull"
                    ],
                    "light": [
                        "on",
                        "off"
                    ]
                },
                "dry": {
                    "temperatures": {
                        "F": {
                            "isNative": true,
                            "values": [
                                62,
                                63,
                                64,
                                65,
                                66,
                                67,
                                68,
                                69,
                                70,
                                71,
                                72,
                                73,
                                74,
                                75,
                                76,
                                77,
                                78,
                                79,
                                80,
                                81,
                                82,
                                83,
                                84,
                                85,
                                86
                            ]
                        },
                        "C": {
                            "isNative": false,
                            "values": [
                                17,
                                18,
                                19,
                                20,
                                21,
                                22,
                                23,
                                24,
                                25,
                                26,
                                27,
                                28,
                                29,
                                30
                            ]
                        }
                    },
                    "swing": [
                        "stopped",
                        "rangeFull"
                    ],
                    "light": [
                        "on",
                        "off"
                    ]
                },
                "auto": {
                    "temperatures": {
                        "F": {
                            "isNative": true,
                            "values": [
                                62,
                                63,
                                64,
                                65,
                                66,
                                67,
                                68,
                                69,
                                70,
                                71,
                                72,
                                73,
                                74,
                                75,
                                76,
                                77,
                                78,
                                79,
                                80,
                                81,
                                82,
                                83,
                                84,
                                85,
                                86
                            ]
                        },
                        "C": {
                            "isNative": false,
                            "values": [
                                17,
                                18,
                                19,
                                20,
                                21,
                                22,
                                23,
                                24,
                                25,
                                26,
                                27,
                                28,
                                29,
                                30
                            ]
                        }
                    },
                    "swing": [
                        "stopped",
                        "rangeFull"
                    ],
                    "light": [
                        "on",
                        "off"
                    ]
                }
            }
        },
        "smartMode": {
            "enabled": false
        },
        "measurements": {
            "time": {
                "time": "2025-10-29T17:56:07.514358Z",
                "secondsAgo": 27
            },
            "temperature": 18.3,
            "humidity": 0,
            "feelsLike": 18.3,
            "rssi": -57
        }
    }
]`
